// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvh2BGL1BNZdpeiwdO93XycgBwUERvfkQ',
    appId: '1:874671329578:web:956a733f57a09e63794e53',
    messagingSenderId: '874671329578',
    projectId: 'famfunds-1c6e4',
    authDomain: 'famfunds-1c6e4.firebaseapp.com',
    storageBucket: 'famfunds-1c6e4.firebasestorage.app',
    measurementId: 'G-Y6XTDPNS8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOLKv1bd0hbSDH4qIiq1ZcoYldlpa1j9g',
    appId: '1:874671329578:android:9ca22e6a68afdd66794e53',
    messagingSenderId: '874671329578',
    projectId: 'famfunds-1c6e4',
    storageBucket: 'famfunds-1c6e4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv8SJUYBmytONkzsxQU51rJVS6q_0xoL8',
    appId: '1:874671329578:ios:06a750830aea2111794e53',
    messagingSenderId: '874671329578',
    projectId: 'famfunds-1c6e4',
    storageBucket: 'famfunds-1c6e4.firebasestorage.app',
    iosBundleId: 'com.example.finfamily',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv8SJUYBmytONkzsxQU51rJVS6q_0xoL8',
    appId: '1:874671329578:ios:06a750830aea2111794e53',
    messagingSenderId: '874671329578',
    projectId: 'famfunds-1c6e4',
    storageBucket: 'famfunds-1c6e4.firebasestorage.app',
    iosBundleId: 'com.example.finfamily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvh2BGL1BNZdpeiwdO93XycgBwUERvfkQ',
    appId: '1:874671329578:web:a7417285aaebf036794e53',
    messagingSenderId: '874671329578',
    projectId: 'famfunds-1c6e4',
    authDomain: 'famfunds-1c6e4.firebaseapp.com',
    storageBucket: 'famfunds-1c6e4.firebasestorage.app',
    measurementId: 'G-9D6MFGKM36',
  );
}
